// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoParqueoFinal.Data;

#nullable disable

namespace ProyectoParqueoFinal.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250417235152_ActualizacionOnDeleteCascade")]
    partial class ActualizacionOnDeleteCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoParqueoFinal.Models.Bitacora", b =>
                {
                    b.Property<int>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBitacora"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParqueoIdParqueo")
                        .HasColumnType("int");

                    b.Property<string>("TipoIngreso")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("VehiculosIdVehiculo")
                        .HasColumnType("int");

                    b.HasKey("IdBitacora");

                    b.HasIndex("ParqueoIdParqueo");

                    b.HasIndex("VehiculosIdVehiculo");

                    b.ToTable("Bitacoras");
                });

            modelBuilder.Entity("ProyectoParqueoFinal.Models.Parqueo", b =>
                {
                    b.Property<int>("IdParqueo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParqueo"));

                    b.Property<int>("CapacidadAutomoviles")
                        .HasColumnType("int");

                    b.Property<int>("CapacidadLey7600")
                        .HasColumnType("int");

                    b.Property<int>("CapacidadMotocicletas")
                        .HasColumnType("int");

                    b.Property<string>("NombreParqueo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdParqueo");

                    b.ToTable("Parqueos");
                });

            modelBuilder.Entity("ProyectoParqueoFinal.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroCarne")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("RequiereCambioPassword")
                        .HasColumnType("bit");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoParqueoFinal.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NumeroPlaca")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("UsaEspacio7600")
                        .HasColumnType("bit");

                    b.Property<int>("UsuariosIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("UsuariosIdUsuario");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("ProyectoParqueoFinal.Models.Bitacora", b =>
                {
                    b.HasOne("ProyectoParqueoFinal.Models.Parqueo", "Parqueo")
                        .WithMany("Bitacoras")
                        .HasForeignKey("ParqueoIdParqueo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoParqueoFinal.Models.Vehiculo", "Vehiculo")
                        .WithMany("Bitacoras")
                        .HasForeignKey("VehiculosIdVehiculo")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parqueo");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ProyectoParqueoFinal.Models.Vehiculo", b =>
                {
                    b.HasOne("ProyectoParqueoFinal.Models.Usuario", "Usuario")
                        .WithMany("Vehiculos")
                        .HasForeignKey("UsuariosIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoParqueoFinal.Models.Parqueo", b =>
                {
                    b.Navigation("Bitacoras");
                });

            modelBuilder.Entity("ProyectoParqueoFinal.Models.Usuario", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("ProyectoParqueoFinal.Models.Vehiculo", b =>
                {
                    b.Navigation("Bitacoras");
                });
#pragma warning restore 612, 618
        }
    }
}
